### ISSUE TITLE
package manager x lilypond version manager

### ISSUE THREAD

**Issue by igneus** [noteflakes/lyp#11]
I don't think it is a very good idea to have one tool manage both lilypond versions and lilypond code packages. I suggest following the Single Responsibility Principle and splitting lyp in two separate tools: a lilypond version manager allowing one to install several lilypond versions easily and switch between them, and a package manager, working simply with the lilypond currently in PATH. (Regardless of it being provided by the version manager or installed as a single system-wide lilypond instance.)

**Comment by igneus** [comment]
As for the lilypond version manager, there already is [lilyvm](https://github.com/olsonpm/lilyvm)

**Comment by ciconia** [comment]
I disagree. The goal for lyp is to be a comprehensive tool for developing and sharing lilypond code ("packages"). In order to provide package loading functionality, lyp needs to wrap the lilypond executable.  Also, package developers need to be able to test their code on different versions of lilypond. Lyp already provides a command (`lyp test`) to run package tests using the currently selected version of lilypond, and an upcoming feature would be running package tests on multiple versions of lilypond, which can be a tremendous aid for people writing lilypond libraries (since things break quite often in Lilypond).

Yes, you can use lilyvm, but currently it only supports linux (not tested on Mac OSX), and it has quite limited testing. Also, the fact that is written in shell scripts means it will probably never support Windows, which is if I'm not mistaken quite popular among Lilypond users. Lyp, on the other hand, already supports Mac OSX and Linux, (with Windows support already being worked on, probably another couple of weeks), and is very well tested.

Besides, there's nothing stopping you from using lyp together with lilyvm, or any stock installation of lilypond. Lyp would recognize any version of lilypond on the user's $PATH.

**Comment by ciconia** [comment]
This was a real pain in the ass but I finally got it to work on Windows (55053bd). Well anyway I'm closing this as a won't fix.

**Comment by igneus** [comment]
Ok. I was just writing a follow-up, but if you don't want to discuss architecture, I won't bother you with any more musings on this topic.

**Comment by ciconia** [comment]
If you have a response feel free to post it here or in another issue. There's no bother.

**Comment by igneus** [comment]
I understand that lyp is, as a lilypond version manager, supreme to lilyvm with regard to portability, functionality and reliability. Great.

> Besides, there's nothing stopping you from using lyp together with lilyvm, or any stock installation of lilypond. Lyp would recognize any version of lilypond on the user's $PATH.

-- Even greater - that's a feature which I really appreciate.

> The goal for lyp is to be a comprehensive tool for developing and sharing lilypond code ("packages"). In order to provide package loading functionality, lyp needs to wrap the lilypond executable. Also, package developers need to be able to test their code on different versions of lilypond.

-- As a preferable solution to address the described problem area I still see two separate layers (i.e. two separate executables, not necessarily two gems):

1. lilypond version manager
2. lilypond wrapper injecting packages

For testing of lilypond code across several lilypond versions either a third thin layer can be added or it can be solved by a general feature of the version manager (not knowing anything about the package code injector) "execute X across versions V1 ... Vn" where X can be invocation of the injector or anything else.

My ideological background is in the [Art of Unix Programming, I.1](http://www.catb.org/esr/writings/taoup/html/ch01s06.html), especially in the Rule of Modularity and Rule of Composition.

(And I am eventually willing to contribute not only ideology, but also code.)

**Comment by ciconia** [comment]
> As a preferable solution to address the described problem area I still see two separate layers (i.e. two separate executables, not necessarily two gems):
> 
> 1. lilypond version manager
> 2. lilypond wrapper injecting packages

But how is this really different than the present situation (where you actually have two executables, `lyp`and `lilypond`)? The only difference would be that you'll have a third executable, so instead of running `lyp install lilypond@stable` you'll run `lvm install stable`. Am I missing something?

> For testing of lilypond code across several lilypond versions either a third thin layer can be added or it can be solved by a general feature of the version manager

Again, how does this improve the code quality or user experience?

> (not knowing anything about the package code injector)

Please read the code before responding: [resolver](https://github.com/noteflakes/lyp/blob/master/lib/lyp/resolver.rb), [wrapper](https://github.com/noteflakes/lyp/blob/master/lib/lyp/wrapper.rb), [wrapper template](https://github.com/noteflakes/lyp/blob/master/lib/lyp/templates/deps_wrapper.rb), [scheme interface](https://github.com/noteflakes/lyp/blob/master/lib/lyp/etc/lyp.ly)

> My ideological background is in the Art of Unix Programming, I.1, especially in the Rule of Modularity and Rule of Composition.

Don't take it personal but I find little use for ideology. Of course, if you have ideas on how to improve the functioning, user experience, or code quality please let me know. But frankly cutting up the code a bit different, I don't see how this improves things.

> (And I am eventually willing to contribute not only ideology, but also code.)

Please do :-)
