### ISSUE TITLE
lyp flatten error

### ISSUE THREAD

**Issue by pihentagy** [noteflakes/lyp#45]
After successfully rendering my file with `lilypond angelus.ly`, I cannot flatten the `.ly` file.
```
lyp flatten angelus.ly 
No such file or directory @ rb_sysopen - /home/pihentagy/gdrive/kotta/Ckotta/darabok/AngelusPastoribus/deutsch.ly
```

**Comment by ciconia** [comment]
I'll try to push out a release later. For now you can try it as a gem (version 1.3.3).

**Comment by ciconia** [comment]
Yes, this is intended, and is standard lilypond behaviour. If you wish to include a certain file only once, lyp provides the non-standard [\pincludeOnce](https://github.com/noteflakes/lyp#including-files) command.

FWIW, the `deutsch.ly` file you're including basically consists of a single command, which you can use instead of including the file:

```lilypond
\language "deutsch"
```
